### ISSUE TITLE
Use import as a good practice to split modules

### ISSUE THREAD

**Issue by argades** [jhipster/jdl-samples#13]
It would be a good idea to use file imports as good practice. That is, having a file where all tables and relationships are defined and in the definition of the backend, frontend and microservices, the file defining tables and relationships in each of them is imported and using those that are necessary for each one of them they.

**Comment by deepu105** [comment]
This is not the right place for this, if you have a feature request I suggest you look at the https://github.com/jhipster/generator-jhipster/issues tracker
