### ISSUE TITLE
Sample relationships with microservices

### ISSUE THREAD

**Issue by devorbitus** [jhipster/jdl-samples#5]
None of the current samples have microservices. It would be helpful to see a collection of microservice jh files.

**Comment by PierreBesson** [comment]
@devorbitus Can you submit a PR ? Otherwise we should be able to add this from the jdl we use in demos.

**Comment by jdubois** [comment]
Yes, we should clean up the existing samples also.

**Comment by deepu105** [comment]
we now have some microservice samples
