### ISSUE TITLE
How to add database schema property to multiple entities.    

### ISSUE THREAD

**Issue by mEEt126** [jhipster/jdl-samples#57]
Hello All, 
Currently I'm working on IOT project where we have multiple entities related to multiple DB schemas. We are planning to bootstrap our application using JHIPSTER 8 Beta version. Kindly suggest how to "How to add database schema property to multiple entities in JDL files?".  
Help is Appreciated!
Thank you.

**Comment by mshima** [comment]
There is no support for multiples schemas.
You should open a feature request at [generator-jhipster](https://github.com/jhipster/generator-jhipster)
