### ISSUE TITLE
How does 'restricted' in the online-store example work?

### ISSUE THREAD

**Issue by lucvandewall** [jhipster/jdl-samples#8]
In de online-store example there is one Boolean (with the name 'restricted') in the entity Wishlist which gets a prefix of "jhi_" in a sql database. In the documentation I cannot find any details whether 'restricted' is a reserved word.

**Comment by gmarziou** [comment]
We have it only in our [Oracle reserved words list](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/reserved_keywords.js#L109), you could try removing the prefix in Liquibase migration and `@Column` to see if it breaks something.

**Comment by jdubois** [comment]
I'm closing this as we have the explanation - thanks @gmarziou !

**Comment by gmarziou** [comment]
This list comes from  Oracle: https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm

Maybe all words do not apply in all contexts but we can't test everything especially with closed source databases like Oracle.
